language: c

compiler:
  - gcc
  
branches:
  only:
  - master

before_install:
#  - sudo apt-get install -qq libxml2-dev
  - ldd `which xmllint`
  - xmllint --version
#  - xml --version
  - xmlstarlet --version
  
script: gcc -o main main.c
