language: c

compiler:
  - gcc
  
branches:
  only:
  - master

before_install:
  - NS=""
#  - NS="_:"
  - sudo apt-get install -qq xmlstarlet
  - xmlstarlet --version
  - xmlstarlet sel -t -v '/${NS}project/${NS}dependencies/${NS}dependency/${NS}artifactId' pom.xml

script: gcc -o main main.c
