language: c

compiler:
  - gcc
  
branches:
  only:
  - master

before_install:
  - echo -e 'setns x=http://maven.apache.org/POM/4.0.0\ncat /x:project/x:dependencies/x:dependency/x:artifactId/text()' | xmllint --shell pom.xml | grep -v / |sort|uniq

script: gcc -o main main.c
