language: c

compiler:
  - gcc
  
branches:
  only:
  - master

before_install:
  - echo $SHELL
  - NS=""
#  - NS="_:"
  - sudo apt-get install -qq xmlstarlet
  - xmlstarlet --version
  - xmlstarlet sel -t -v "/project/dependencies/dependency/artifactId" pom.xml

script: gcc -o main main.c
